### PR TITLE
Refactored filter API

### PR DESCRIPTION
**Pull request by whitepaperclip**
OK, finally refactored the API, and updated all tests to pass. New API for labels:

`filter [:name, email: [label: "EMail Address"]]`

API example for ordering a `belongs_to` association:

`filter [post: [order_by: [asc: :name]]]`

I spent a lot of time thinking about this, and I ended up removing `:only` and `:except` as options. A few reasons:

1. `:only` is basically useless. If you have an explicit list of filters, wrapping it in an `:only` keyword doesn't do anything but add extra code. Since this refactor breaks backwards compatibility, I figured we might as well kill it off.

2. `:except` - this one is a little trickier to justify, but in the end I'd rather take a principled approach of having to explicitly specify which filters you want to enable for a particular screen. If we leave this here and let users specify `:except`, they'll end up adding filters to various admin screens by simply adding new fields to their models.

### CODE REVIEW

**Comment by whitepaperclip** [comment]
Small note: this does need a test to protect against regression bugs with `order_by`, but I wasn't sure how to effective add this test in. Could use some help there.

**Comment by viniciussbs** [comment]
I'm looking forward to the merge. 🙂

**Comment by whitepaperclip** [comment]
@smpallen99 ping

**Comment by smpallen99** [comment]
I took at look at this last night. Want to pull down the changes and test against couple of my ex_admin projects before I merge.

**Comment by whitepaperclip** [comment]
@smpallen99 ping 😄

**Comment by smpallen99** [comment]
got ur ping @whitepaperclip I'll bump this on my todo list

**Comment by smpallen99** [comment]
I really don't see how removing `:except` option adds any value. Of course it will add new fields to the filter, but not using the filter macro has the same behaviour. The once scenario where I use this is on a User schema where I want to removed password fields from the the filter. The `:except` option is great for this. 

I would like to see this option added back in unless we get overwhelming objection from the community.

**Comment by whitepaperclip** [comment]
@smpallen99 Few questions for supporters of `:except`:

1. Should `:except` automatically include the `:id` field, or not?
2. If a new association is created between two models, and the model in question has a new `:association_id` field, does this get added automatically?
3. How does `:except` work with regular filters? Should the following be acceptable: `filter [:name, :other_field, except: [:password]]`? What fields would that actually end up displaying?
4. What if a model has a field named `:except`? 😄 

I should point out that it would be impossible to specify any sort of filter options if `:except` is available. For example: `filter [title: [label: "Name"]], except: [:password]`.

**Comment by smpallen99** [comment]
@whitepaperclip Ok, I can now see why you removed `:except`. Basically, you've changed the API to an all-or-explicit approach. The way I originally designed this was allow allow customizing  
specific fields, without having to explicitly list every field. This approach gave the user enough flexibility to allow new fields to automatically appear, or specify an explicit list. But the downside is that the customization of individual fields is done through options and not in the explicit list as you have designed.

I like your design, but I'm concerned with the regression impacts. For example, I have user model that has lot of fields. Today, I have 

```elixir
  filter except: [:encrypted_password], labels: [name: "Full Name"]
```
and now I will have to use
```elixir
  filter [name: [label: "Full Name"], :email, :username, :email, :active, :expire_on, :reset_password_token, 
    :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at, 
    :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :failed_attempts, :locked_at, :unlock_token,
    :confirmation_token, :confirmed_at, :confirmation_sent_at, :inserted_at, :updated_at]
```

This creates a lot of noise compared to the current approach. 

I'm going to sleep on this.

**Comment by whitepaperclip** [comment]
@smpallen99 Yikes! That's definitely way more than I had anticipated anyone would ever use. In my projects I typically only have 3-4 filters per model, since that's all I usually need to filter the records down to what I'm actually looking for.

I looked into how ActiveAdmin handles this issue. They don't allow `:except` either, for the reasons above, so you have to do it this way: https://github.com/activeadmin/activeadmin/issues/4064

Throwing an idea out there:

```elixir
filter name: [label: "Full Name"]
filter supervisor: [order_by: [asc: :name]]
filter except: [:encrypted_password]
```

This would require retaining state somehow; each time `filter()` is called it would have to update `defn`.

**Comment by smpallen99** [comment]
It already retains state. https://github.com/smpallen99/ex_admin/blob/master/lib/ex_admin/register.ex#L105 That is what the `accumulate: true` option does you register an attribute. 

However, I was thinking that having both approaches might work. We could support your new API, or they could use the old api. I'm still thinking about it :)

**Comment by whitepaperclip** [comment]
Another option would be another function altogether (`Enum.filter` vs. `Enum.reject`):

`remove_filter [:encrypted_password, :password_salt]`

Though, I'm still bugged by this solution because it just doesn't feel very "Elixir-y". I would rather follow the conventions of the language by making the filters explicit, rather than implicit. After searching for a bit, I can't find any instances of `:except` being used in core Elixir APIs, other than `import()`. (I would be weary of calling `import` with `:except`, anyway.)

Have you used all of those filters at least once? I can't think of a situation where I'd want to filter a list of users by their `unlock_token`, or their `remember_created_at`.

**Comment by smpallen99** [comment]
Lets go with the explicit approach.

**Pull request merged**
