### PR TITLE
Accept footer configuration option, or revert to default

### PR DESCRIPTION
**Pull request by whitepaperclip**
Addresses issue #272, and also permanently fixes the end year in the copyright.

### CODE REVIEW

**Comment by whitepaperclip** [comment]
Hmm.

`** (UndefinedFunctionError) function NaiveDateTime.utc_now/0 is undefined or private`

Updated to use `DateTime` instead.

**Comment by smpallen99** [comment]
First, thanks for the idea of keeping the copyright up to date. I like it :)

I did not provide a way to override the powered by on the footer because I wanted to keep mention of my company who sponsored the original development of this project. But I guess that's just a pipe dream....

Before merging the footer change, I would to think/discuss/review the whole approach of the layout. Do you think separate config items for each part is the right approach? There are a couple other options. We could have an option to copy over the complete layout file into the project's web directory so they can customize it. Another idea is to break it into a bunch of smaller partials with the ability to override individual partials with through config, or compile time lookup.

I think it make sense to come up with a strategy now so it will be less disruptive if we introduce this footer approach now, and revamp the strategy down the road.

Thought?

cc @whitepaperclip

**Comment by whitepaperclip** [comment]
Thanks for considering this.

> We could have an option to copy over the complete layout file into the project's web directory so they can customize it.

The immediate downside I can think of to this would be that managing changes between the master branch and the user's changes would probably be painful. We would always have to copy over the new layout files while attempting to preserve changes. Not a fan.

>Another idea is to break it into a bunch of smaller partials with the ability to override individual partials with through config, or compile time lookup.

I do like the partial approach! It might require a significant amount of refactoring, though. I'd be willing to do it, though. It takes me back to `rails g devise:views`. :)

We *could* keep the config options for now, and plan on a more robust theme customization plan (using partials) for 0.9.0. Thoughts?

(Also, sorry about the copyright notice. My hands are tied when it comes to public-facing government projects that use open source libraries. `:(`)

**Comment by smpallen99** [comment]
Ok, I'll accept this approach. Can you add some docs for the new option please.

**Comment by whitepaperclip** [comment]
Definitely. I couldn't find docs for config options. Where are those?

**Comment by whitepaperclip** [comment]
Okay, added documentation to `lib/ex_admin.ex`.

**Comment by smpallen99** [comment]
Thanks for another contribution @whitepaperclip

**Comment by smpallen99** [comment]
Also added footer to comments in `config/config.exs`

**Pull request merged**
