### PR TITLE
Admin controllers refactoring and URL helpers based on Router

### PR DESCRIPTION
**Pull request by romul**
Details in #115

### CODE REVIEW

**Comment by smpallen99** [comment]
Great contribution @romul. Thanks a bunch...Steve

**Comment by smpallen99** [comment]
@romul

Merged! I just tried merging ecto-1.1 into master, but it did not go very well. Could you do this merge?

Thanks,
Steve

**Comment by romul** [comment]
@smpallen99 
> I just tried merging ecto-1.1 into master, but it did not go very well. Could you do this merge?

Yeah, it's getting a bit tricky, b/c of ecto-2 related changes in the master. Will do.

**Comment by smpallen99** [comment]
I think the only breaking change in ecto2 is changeset.model to changeset.data. I wonder if we  should create solution that handles both cases. Either at run time or we compile time. 

That way, we might be able to do everything on master. Would save some work. What do you think?

**Comment by romul** [comment]
@smpallen99 Honestly it's really tedious to work in two parallel branches, so I love idea to do everything on master.
Maybe something like 
```elixir
def changeset_data(changeset) do
  Map.get(changeset, :data) || Map.get(changeset, :model)
```
will work.

**Comment by romul** [comment]
@smpallen99 Or could we just work on master with Ecto 2 and put only bug fixes to ecto-1.1?

**Comment by smpallen99** [comment]
I'm not ready to swing my active projects that use ExAdmin over to Ecto2. I've nothing but issues trying to get Ecto2 working reliably. So, I would like to try your suggestion above. And if we do have issues keeping master compatible with ecto1, then we keep the ecto-1.1 branch for bugfix only.

**Pull request merged**
