### PR TITLE
Menu should support :none for registered resources

### PR DESCRIPTION
**Pull request by whitepaperclip**
Could we consider changing the API to `menu false`, so that it's consistent with other ExAdmin functions?

### CODE REVIEW

**Comment by whitepaperclip** [comment]
Added implementation for rendering NaiveDateTime.

**Comment by smpallen99** [comment]
@whitepaperclip none should already be supported with `menu none: true` per [this](https://github.com/smpallen99/ex_admin/blob/75d92ce638071690fd4512d0ba603d8cef46c918/lib/ex_admin/navigation.ex#L11) However, I agree that `menu false` would be more consistent with other macros. 

Can you change this PR to use `false` instead? Also, could you add some docs for it. 

Thanks,
Steve

**Comment by whitepaperclip** [comment]
@smpallen99 Sure, I will change this tomorrow AM. I think the confusion stems from the documentation: https://hexdocs.pm/ex_admin/ExAdmin.Register.html#menu/1

(Note the example: `menu :none`)

**Comment by smpallen99** [comment]
agree, I screwed up the docs :(

**Comment by whitepaperclip** [comment]
No worries! Should be all patched up tomorrow, including updated docs.

**Comment by whitepaperclip** [comment]
Alright, updated menu() function and docs as promised. I believe `menu none: true` will still work, because it just gets passed in as regular options, so it is backwards compatible.

**Comment by smpallen99** [comment]
Thanks a bunch for the contribution!!

**Pull request merged**
