### PR TITLE
Extend Travis build matrix

### PR DESCRIPTION
**Pull request by samhamilton**
Hello, 

This is a small addition so that Travis builds against a wider and newer range of Elixir and Erlang versions. 

Thanks
Sam

### CODE REVIEW

**Comment by smpallen99** [comment]
This is going to extend the travis checks by a significant amount. By looking at the current status, I think its now going to take over 30 minutes to complete. What do you think about 2 additional elixir and 2 additional otp versions?

**Comment by samhamilton** [comment]
Sure - how about the leaving in the "oldest supported target" which I would assume means 18.2.1 and 1.3.1 and the latest 19.3 and 1.4.2? What would be the middle ground?

**Comment by samhamilton** [comment]
Ok - so Travis seems to need to be quite specific around the OTP version but reasonably flexible for the Elixir version. This now reduces the build time quite a lot. Does that combo work for you? 

One last question, should the OTP 18.2.1 be bumped to 18.3 as it is the latest in the 18 series? Or was there a specific reason for the 18.2.1 version to be included?

**Comment by smpallen99** [comment]
Yes, you can bump OTP to 18.3. and yes, thats a much better run time 👍

**Comment by samhamilton** [comment]
Perfect. Updated. Thanks so much

**Pull request merged**
